# Generated by Django 2.0.3 on 2018-03-14 21:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('sub_post', django.db.models.manager.Manager()),
            ],
        ),
    ]
